In [1]:
## importing all libraries and dependencies
import pandas as pd
import numpy as np
import os
from os import listdir
import glob
from os.path import isfile, join
import shutil
import PIL
from PIL import Image
import random
from random import sample
import math
from heapq import merge
from random import *
import secrets
from scipy.stats import spearmanr
from scipy import stats
import matplotlib.pyplot as plt

In [37]:
summary_dir = '/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_summaries/'
all_csvs = [f for f in listdir(summary_dir)]
for f in all_csvs:
    one = pd.read_csv(summary_dir + f)
    if one.rho[2]< 0.75:
        shutil.move('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_summaries/' + f, '/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/lowcorr/lowcorr_emobdr/' + f)

In [45]:
#1-match the participants with the questionnaire- make sure youve excluded the summaries of those with lowcorr or those who just need to be excluded
noconsent = []
summary_dir = '/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_summaries/'
summary_csvs = [f for f in listdir(summary_dir)]
summary_files = [t[:-4] for t in summary_csvs]
que_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/qs_numerics.csv')
que_df['workerID'] = que_df['workerID'].astype(pd.StringDtype())
que_df = que_df.loc[que_df.workerID != 'nan']
shrt_quedf= []
for index, row in que_df.iterrows():
    if que_df.workerID[index] in summary_files:
        shrt_quedf.append(row)
    else:
        noconsent.append(que_df.workerID[index])
Tshrt_quedf = pd.DataFrame(shrt_quedf)
Tshrt_quedf

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q49,Q50,task launch time_First Click,task launch time_Last Click,task launch time_Page Submit,task launch time_Click Count,SC0,workerID.1,assignmentID,hitID
3,2/14/2024 11:12,2/14/2024 11:30,0,68.80.194.77,100,1101,1,2/14/2024 11:30,R_5d7CbLrhd85BRAd,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
10,2/14/2024 11:14,2/14/2024 11:39,0,68.224.75.173,100,1489,1,2/14/2024 11:39,R_5soBCZHlctnrD8H,NaN,...,1,2,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
11,2/14/2024 11:16,2/14/2024 11:41,0,173.90.75.108,100,1475,1,2/14/2024 11:41,R_3njywetD1vtEOuu,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
15,2/14/2024 11:34,2/14/2024 12:01,0,216.164.112.118,100,1605,1,2/14/2024 12:01,R_3ydXweczcgtrM2o,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
20,2/14/2024 12:14,2/14/2024 12:35,0,97.87.4.154,100,1250,1,2/14/2024 12:35,R_1eXqtk4juJHxsAV,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
23,2/14/2024 12:16,2/14/2024 12:39,0,98.212.175.7,100,1374,1,2/14/2024 12:39,R_6F4YIV4x5ZVdtCT,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
37,2/14/2024 15:14,2/14/2024 15:39,0,24.241.56.41,100,1454,1,2/14/2024 15:39,R_3n0KV9V85BxwS2i,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
38,2/14/2024 11:17,2/14/2024 11:41,0,35.145.26.145,95,1443,0,2/14/2024 15:41,R_6p2Yz63gjlfDHFN,NaN,...,3,4,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
39,2/14/2024 15:26,2/14/2024 15:45,0,184.56.107.132,100,1173,1,2/14/2024 15:45,R_6tDJVJlFd2UHcw2,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
40,2/14/2024 15:26,2/14/2024 15:48,0,172.250.109.105,100,1334,1,2/14/2024 15:48,R_3YEyKj7r3K9UgPs,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
47,2/14/2024 16:33,2/14/2024 17:05,0,47.40.154.226,100,1905,1,2/14/2024 17:05,R_6S99lriwPxpskrK,NaN,...,2,3,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
66,2/14/2024 17:39,2/14/2024 17:43,0,68.59.231.210,95,246,0,2/14/2024 21:43,R_1X5RY9VtoF3YRAs,NaN,...,2,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
71,2/14/2024 22:05,2/14/2024 22:24,0,47.233.52.144,100,1119,1,2/14/2024 22:24,R_3BkT6ue5Ayf6eHO,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
74,2/14/2024 18:44,2/14/2024 18:48,0,192.203.201.3,95,243,0,2/14/2024 22:48,R_1HzS94JO2F4hRDj,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
79,2/15/2024 1:01,2/15/2024 1:26,0,191.96.106.203,100,1504,1,2/15/2024 1:26,R_6ajPANGRrbulRHH,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
82,2/15/2024 2:56,2/15/2024 3:19,0,71.29.113.24,100,1361,1,2/15/2024 3:19,R_7eG7VeKXbSdks1z,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
91,2/15/2024 9:28,2/15/2024 9:47,0,97.116.1.237,100,1145,1,2/15/2024 9:47,R_1PI0fictbamfFAZ,NaN,...,1,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
93,2/15/2024 12:13,2/15/2024 12:34,0,98.212.175.7,100,1216,1,2/15/2024 12:34,R_1pfCUKiwd3aJe1l,NaN,...,2,2,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
99,2/15/2024 7:52,2/15/2024 8:50,0,50.24.50.122,95,3462,0,2/15/2024 13:23,R_3pYwv0JmcUXHRJ4,NaN,...,2,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
100,2/15/2024 13:06,2/15/2024 13:25,0,99.113.207.100,100,1123,1,2/15/2024 13:25,R_7ONG3gsFaYjVGXb,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
101,2/15/2024 13:05,2/15/2024 13:26,0,172.58.89.80,100,1265,1,2/15/2024 13:26,R_5gA6ssOTEB1IgP5,NaN,...,1,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
116,2/15/2024 17:56,2/15/2024 18:18,0,108.183.42.69,100,1285,1,2/15/2024 18:18,R_72z565UQS9zBRwX,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
119,2/15/2024 16:33,2/15/2024 16:40,0,73.21.153.218,95,402,0,2/15/2024 20:40,R_5EFRiT2Bsb1tLv4,NaN,...,1,2,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
121,2/15/2024 22:04,2/15/2024 22:27,0,174.196.193.126,100,1373,1,2/15/2024 22:27,R_6nTTmcHmAJnTGmz,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
124,2/16/2024 2:16,2/16/2024 2:35,0,68.59.231.210,100,1145,1,2/16/2024 2:35,R_1CZ2wNGVkbJTau7,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
128,2/16/2024 4:33,2/16/2024 4:52,0,108.53.209.115,100,1136,1,2/16/2024 4:52,R_30xAVTZvyEXcl3I,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
130,2/16/2024 7:02,2/16/2024 7:22,0,174.103.163.85,100,1223,1,2/16/2024 7:22,R_6k7CSNwluaKYqyt,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
135,2/16/2024 11:01,2/16/2024 11:26,0,71.72.225.168,100,1512,1,2/16/2024 11:26,R_1h9FBdd148Gpy84,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
138,2/16/2024 13:24,2/16/2024 13:44,0,47.224.128.127,100,1191,1,2/16/2024 13:44,R_7KD8Sf1HUCC1e8V,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
152,2/17/2024 11:43,2/17/2024 12:04,0,172.56.44.192,100,1226,1,2/17/2024 12:04,R_79tPodyPTbu0PmS,NaN,...,2,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
153,2/17/2024 12:24,2/17/2024 12:55,0,50.24.50.122,95,1859,0,2/17/2024 16:55,R_5CPSBsj1SU1fBIx,NaN,...,2,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
154,2/19/2024 12:37,2/19/2024 12:56,0,104.3.54.201,100,1128,1,2/19/2024 12:56,R_7i3VpdRQhLXkzTQ,NaN,...,1,1,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN
158,2/19/2024 12:54,2/19/2024 13:13,0,24.176.0.73,100,1173,1,2/19/2024 13:13,R_5VBix6gLBmPQIhz,NaN,...,2,3,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
160,2/19/2024 13:04,2/19/2024 13:27,0,174.240.114.226,100,1373,1,2/19/2024 13:27,R_6flc1nSAj8ZXja9,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
161,2/19/2024 13:26,2/19/2024 13:47,0,68.184.30.135,100,1266,1,2/19/2024 13:47,R_5pkE3jZZBG2k7yF,NaN,...,2,2,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
164,2/19/2024 13:38,2/19/2024 13:58,0,98.212.175.7,100,1185,1,2/19/2024 13:58,R_5TosQHTU6m4DB8R,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
171,2/19/2024 15:42,2/19/2024 16:03,0,98.252.216.79,100,1247,1,2/19/2024 16:03,R_1rJuminzQAAymmx,NaN,...,2,2,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN
172,2/19/2024 15:58,2/19/2024 16:23,0,184.56.107.132,100,1533,1,2/19/2024 16:23,R_3VlWdBPvnyhYqkh,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
178,2/19/2024 16:54,2/19/2024 17:14,0,75.184.124.108,100,1167,1,2/19/2024 17:14,R_1tBL3h4t9JTmF45,NaN,...,1,1,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
182,2/19/2024 18:41,2/19/2024 19:11,0,47.40.154.226,100,1822,1,2/19/2024 19:11,R_3suByYX82TyAYsF,NaN,...,1,2,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
193,2/20/2024 5:54,2/20/2024 5:55,0,102.129.145.121,95,81,0,2/20/2024 9:55,R_1TwA7WdqCtEJbXj,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
201,2/20/2024 10:03,2/20/2024 10:29,0,69.109.249.160,95,1583,0,2/20/2024 14:29,R_1aD2Fk6ZaZk6TWF,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
214,2/21/2024 22:07,2/21/2024 22:42,0,68.196.71.190,100,2104,1,2/21/2024 22:42,R_7MMd9o2MXvsquDX,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
215,2/22/2024 15:01,2/22/2024 15:20,0,24.49.58.42,100,1108,1,2/22/2024 15:20,R_5QL4CROMUBcBHNx,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN

In [46]:
len(Tshrt_quedf.workerID.unique())

37

In [47]:
#2-have one dataframe slice for each categories that categorizes Depression, Anxiety, Stress:
dep_df = Tshrt_quedf[["workerID", "Q32", "Q34", "Q39", "Q42", "Q45", "Q46", "Q50"]]
anx_df = Tshrt_quedf[["workerID", "Q31", "Q33", "Q36", "Q38", "Q44", "Q48", "Q49"]]
str_df = Tshrt_quedf[["workerID", "Q29", "Q35", "Q37", "Q40", "Q41", "Q43", "Q47"]]

dep_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

In [48]:
#4-have an overall score for the three categories DAS for each participant (calculated in excel) and label them as normal, moderate, severe etc.
dep_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

## for dep
dep_csv.loc[dep_csv['Dsum'] <= 9, 'Dlabel'] = 'Normal'
dep_csv.loc[(dep_csv['Dsum'] >= 10) & (dep_csv['Dsum'] <= 13), 'Dlabel'] = 'Mild'
dep_csv.loc[(dep_csv['Dsum'] >= 14) & (dep_csv['Dsum'] <= 20), 'Dlabel'] = 'Moderate'
dep_csv.loc[(dep_csv['Dsum'] >= 21) & (dep_csv['Dsum'] <= 27), 'Dlabel'] = 'Severe'
dep_csv.loc[dep_csv['Dsum'] >= 28, 'Dlabel'] = 'Extreme'

anx_csv.loc[anx_csv['Asum'] <= 7, 'Alabel'] = 'Normal'
anx_csv.loc[(anx_csv['Asum'] >= 8) & (anx_csv['Asum'] <= 9), 'Alabel'] = 'Mild'
anx_csv.loc[(anx_csv['Asum'] >= 10) & (anx_csv['Asum'] <= 14), 'Alabel'] = 'Moderate'
anx_csv.loc[(anx_csv['Asum'] >= 15) & (anx_csv['Asum'] <= 19), 'Alabel'] = 'Severe'
anx_csv.loc[anx_csv['Asum'] >= 20, 'Alabel'] = 'Extreme'

str_csv.loc[str_csv['Ssum'] <= 14, 'Slabel'] = 'Normal'
str_csv.loc[(str_csv['Ssum'] >= 15) & (str_csv['Ssum'] <= 18), 'Slabel'] = 'Mild'
str_csv.loc[(str_csv['Ssum'] >= 19) & (str_csv['Ssum'] <= 25), 'Slabel'] = 'Moderate'
str_csv.loc[(str_csv['Ssum'] >= 26) & (str_csv['Ssum'] <= 33), 'Slabel'] = 'Severe'
str_csv.loc[str_csv['Ssum'] >= 34, 'Slabel'] = 'Extreme'

dep_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

In [50]:
#5- create a csv with all the sums and labels (created in excel) along with dur bias scores. Make sure workerID == participant and make sure the questions have the right labels in the numeric_csv cz demographic Qs may have same numbers 
sum_labels = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/DASbdr_sumlabels.csv')
newdf = pd.DataFrame(np.repeat(sum_labels.values, 10, axis=0)) # you dont even need to repeat -____-
newdf.columns = sum_labels.columns

bias_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/pt_dur_bdrcond2.csv')
tst_df = pd.merge(newdf, bias_df, on= 'participant')
tst_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dur_DAS.csv')

In [51]:
bias_df2 = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/emobdr_dur_anova.csv')
tst_df2 = pd.merge(sum_labels, bias_df2, on= 'participant')
tst_df2.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/bdrreg_DAS2.csv')

C:\Users\ayesh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (105) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [52]:
tst_df2

,Unnamed: 0_x,Unnamed: 0.1_x,participant,Dsum,Dlabel,Asum,Alabel,Ssum,Slabel,DAS_overall,...,key_resp_11_duration,the_end_started,the_end_stopped,key_resp_16_keys,key_resp_16_rt,key_resp_16_duration,rho,p_value,zscr,resp_diff
0,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.455556
1,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,-0.025000
2,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.488889
3,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.630556
4,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.127778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,43,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.170833
5106,43,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.981250
5107,43,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.481250
5108,43,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,1.168750
5109,43,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,1.152083