In [1]:
## importing all libraries and dependencies
import pandas as pd
import numpy as np
import os
from os import listdir
import glob
from os.path import isfile, join
import shutil
import PIL
from PIL import Image
import random
from random import sample
import math
from heapq import merge
from random import *
import secrets
from scipy.stats import spearmanr
from scipy import stats
import matplotlib.pyplot as plt

In [21]:
#1-match the participants with the questionnaire- make sure youve excluded the summaries of those with lowcorr or those who just need to be excluded
summary_dir = '/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_summaries/'
summary_csvs = [f for f in listdir(summary_dir)]
summary_files = [t[:-4] for t in summary_csvs]
que_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/qs_numerics.csv')
que_df['workerID'] = que_df['workerID'].astype(pd.StringDtype())
que_df = que_df.loc[que_df.workerID != 'nan']
shrt_quedf= []
for index, row in que_df.iterrows():
    if que_df.workerID[index] in summary_files:
        shrt_quedf.append(row)
Tshrt_quedf = pd.DataFrame(shrt_quedf)
Tshrt_quedf

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q49,Q50,task launch time_First Click,task launch time_Last Click,task launch time_Page Submit,task launch time_Click Count,SC0,workerID.1,assignmentID,hitID
3,2/14/2024 11:12,2/14/2024 11:30,0,68.80.194.77,100,1101,1,2/14/2024 11:30,R_5d7CbLrhd85BRAd,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
7,2/14/2024 11:17,2/14/2024 11:37,0,70.44.94.194,100,1150,1,2/14/2024 11:37,R_3hXz1pkyQV4LDI1,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
9,2/14/2024 11:19,2/14/2024 11:38,0,172.73.121.193,100,1149,1,2/14/2024 11:38,R_6y3jEuaT6iIuJRd,NaN,...,1,1,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
10,2/14/2024 11:14,2/14/2024 11:39,0,68.224.75.173,100,1489,1,2/14/2024 11:39,R_5soBCZHlctnrD8H,NaN,...,1,2,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
11,2/14/2024 11:16,2/14/2024 11:41,0,173.90.75.108,100,1475,1,2/14/2024 11:41,R_3njywetD1vtEOuu,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2/20/2024 14:41,2/20/2024 15:08,0,174.165.170.150,95,1630,0,2/20/2024 19:08,R_6nOFuPGXEF2HiFj,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
206,2/20/2024 19:20,2/20/2024 19:40,0,98.239.24.74,100,1234,1,2/20/2024 19:40,R_6uNFkZjZcnM1kvf,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
213,2/21/2024 21:15,2/21/2024 21:36,0,24.111.199.72,100,1309,1,2/21/2024 21:36,R_5S18WbQmxuOx8Ah,NaN,...,1,1,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
214,2/21/2024 22:07,2/21/2024 22:42,0,68.196.71.190,100,2104,1,2/21/2024 22:42,R_7MMd9o2MXvsquDX,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
215,2/22/2024 15:01,2/22/2024 15:20,0,24.49.58.42,100,1108,1,2/22/2024 15:20,R_5QL4CROMUBcBHNx,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN

In [25]:
len(Tshrt_quedf.workerID.unique())

96

In [12]:
#2-have one dataframe slice for each categories that categorizes Depression, Anxiety, Stress:
dep_df = Tshrt_quedf[["workerID", "Q32", "Q34", "Q39", "Q42", "Q45", "Q46", "Q50"]]
anx_df = Tshrt_quedf[["workerID", "Q31", "Q33", "Q36", "Q38", "Q44", "Q48", "Q49"]]
str_df = Tshrt_quedf[["workerID", "Q29", "Q35", "Q37", "Q40", "Q41", "Q43", "Q47"]]

dep_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

In [13]:
#4-have an overall score for the three categories DAS for each participant (calculated in excel) and label them as normal, moderate, severe etc.
dep_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

## for dep
dep_csv.loc[dep_csv['Dsum'] <= 9, 'Dlabel'] = 'Normal'
dep_csv.loc[(dep_csv['Dsum'] >= 10) & (dep_csv['Dsum'] <= 13), 'Dlabel'] = 'Mild'
dep_csv.loc[(dep_csv['Dsum'] >= 14) & (dep_csv['Dsum'] <= 20), 'Dlabel'] = 'Moderate'
dep_csv.loc[(dep_csv['Dsum'] >= 21) & (dep_csv['Dsum'] <= 27), 'Dlabel'] = 'Severe'
dep_csv.loc[dep_csv['Dsum'] >= 28, 'Dlabel'] = 'Extreme'

anx_csv.loc[anx_csv['Asum'] <= 7, 'Alabel'] = 'Normal'
anx_csv.loc[(anx_csv['Asum'] >= 8) & (anx_csv['Asum'] <= 9), 'Alabel'] = 'Mild'
anx_csv.loc[(anx_csv['Asum'] >= 10) & (anx_csv['Asum'] <= 14), 'Alabel'] = 'Moderate'
anx_csv.loc[(anx_csv['Asum'] >= 15) & (anx_csv['Asum'] <= 19), 'Alabel'] = 'Severe'
anx_csv.loc[anx_csv['Asum'] >= 20, 'Alabel'] = 'Extreme'

str_csv.loc[str_csv['Ssum'] <= 14, 'Slabel'] = 'Normal'
str_csv.loc[(str_csv['Ssum'] >= 15) & (str_csv['Ssum'] <= 18), 'Slabel'] = 'Mild'
str_csv.loc[(str_csv['Ssum'] >= 19) & (str_csv['Ssum'] <= 25), 'Slabel'] = 'Moderate'
str_csv.loc[(str_csv['Ssum'] >= 26) & (str_csv['Ssum'] <= 33), 'Slabel'] = 'Severe'
str_csv.loc[str_csv['Ssum'] >= 34, 'Slabel'] = 'Extreme'

dep_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dep_df.csv')
anx_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/anx_df.csv')
str_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/str_df.csv')

In [18]:
#5- create a csv with all the sums and labels (created in excel) along with dur bias scores. Make sure workerID == participant and make sure the questions have the right labels in the numeric_csv cz demographic Qs may have same numbers 
sum_labels = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/DASbdr_sumlabels.csv')
newdf = pd.DataFrame(np.repeat(sum_labels.values, 10, axis=0)) # you dont even need to repeat -____-
newdf.columns = sum_labels.columns

bias_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/pt_dur_bdrcond2.csv')
tst_df = pd.merge(newdf, bias_df, on= 'participant')
tst_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/dur_DAS.csv')

In [19]:
bias_df2 = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/emobdr_dur_anova.csv')
tst_df2 = pd.merge(sum_labels, bias_df2, on= 'participant')
tst_df2.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emobdr_questionnaires/bdrreg_DAS2.csv')

C:\Users\ayesh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (105) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [20]:
tst_df2

,Unnamed: 0_x,Unnamed: 0.1_x,participant,Dsum,Dlabel,Asum,Alabel,Ssum,Slabel,DAS_overall,...,key_resp_11_duration,the_end_started,the_end_stopped,key_resp_16_keys,key_resp_16_rt,key_resp_16_duration,rho,p_value,zscr,resp_diff
0,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.455556
1,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,-0.025000
2,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.488889
3,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.630556
4,0,3,A1C59M3HPCO503,8,Normal,10,Moderate,12,Normal,30,...,NaN,NaN,NaN,NaN,NaN,NaN,0.840554,2.406307e-35,1.223058,0.127778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,112,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.170833
5106,112,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.981250
5107,112,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,0.481250
5108,112,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,1.168750
5109,112,215,A4SC8G0149GEG,8,Normal,8,Mild,10,Normal,26,...,NaN,NaN,NaN,NaN,NaN,NaN,0.862097,5.216557e-39,1.301456,1.152083