In [1]:
## importing all libraries and dependencies
import pandas as pd
import numpy as np
import os
from os import listdir
import glob
from os.path import isfile, join
import shutil
import PIL
from PIL import Image
import random
from random import sample
import math
from heapq import merge
from random import *
import secrets
from scipy.stats import spearmanr
from scipy import stats
import matplotlib.pyplot as plt

In [101]:
#1-match the participants with the questionnaire
summary_dir = '/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_summaries/'
summary_csvs = [f for f in listdir(summary_dir)]
summary_files = [t[:-4] for t in summary_csvs]
que_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/qs_numerics.csv')
que_df['workerID'] = que_df['workerID'].astype(pd.StringDtype())
que_df = que_df.loc[que_df.workerID != 'nan']
shrt_quedf= []
for index, row in que_df.iterrows():
    if que_df.workerID[index] in summary_files:
        shrt_quedf.append(row)
Tshrt_quedf = pd.DataFrame(shrt_quedf)
Tshrt_quedf

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q49,Q50,task launch time_First Click,task launch time_Last Click,task launch time_Page Submit,task launch time_Click Count,SC0,workerID.1,assignmentID,hitID
4,12/19/2023 10:44,12/19/2023 10:59,0,76.132.167.35,100,882,1,12/19/2023 10:59,R_3pG4yOfB1Gnxlzi,NaN,...,1,1,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN
5,12/19/2023 10:45,12/19/2023 11:00,0,174.109.164.180,100,898,1,12/19/2023 11:00,R_5wWWoqhs1hOh2w1,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
7,12/19/2023 10:44,12/19/2023 11:03,0,97.124.145.226,100,1117,1,12/19/2023 11:03,R_1WBAn9XXdVNmgAy,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
8,12/19/2023 10:45,12/19/2023 11:06,0,73.214.34.193,100,1243,1,12/19/2023 11:06,R_637agrszNCw5RMR,NaN,...,3,2,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
9,12/19/2023 10:46,12/19/2023 11:06,0,24.96.67.199,100,1213,1,12/19/2023 11:06,R_30wwl7GsAT91euU,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
10,12/19/2023 10:52,12/19/2023 11:09,0,47.210.12.76,100,989,1,12/19/2023 11:09,R_3rDDerGILCioCbC,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
11,12/19/2023 10:48,12/19/2023 11:10,0,72.24.237.2,100,1321,1,12/19/2023 11:10,R_5dXh8rdr8JxohWT,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
12,12/19/2023 10:53,12/19/2023 11:13,0,76.155.6.53,100,1180,1,12/19/2023 11:13,R_5aJpiysfSkMxR0R,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
13,12/19/2023 10:57,12/19/2023 11:14,0,73.198.13.141,100,980,1,12/19/2023 11:14,R_5HnOhwIn8hOwlu2,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
14,12/19/2023 10:50,12/19/2023 11:15,0,71.193.44.237,100,1472,1,12/19/2023 11:15,R_5veRyu58NSwfEUR,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
16,12/19/2023 11:00,12/19/2023 11:24,0,174.218.64.1,100,1477,1,12/19/2023 11:24,R_6MLyPTGZpbMIR2N,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
18,12/19/2023 11:17,12/19/2023 11:34,0,172.59.192.172,100,1017,1,12/19/2023 11:34,R_1eb2uFZLT8dG2JX,NaN,...,2,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
19,12/19/2023 11:16,12/19/2023 11:35,0,76.187.65.25,100,1106,1,12/19/2023 11:35,R_3KSES0uDiVqGPsB,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
22,12/19/2023 11:16,12/19/2023 11:39,0,71.197.85.251,100,1353,1,12/19/2023 11:39,R_5ezfDyGHnSniLTf,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
23,12/19/2023 11:42,12/19/2023 11:58,0,70.16.252.129,100,995,1,12/19/2023 11:58,R_7lSk9CNsp3zsnAZ,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
24,12/19/2023 11:43,12/19/2023 12:01,0,73.250.52.100,100,1074,1,12/19/2023 12:01,R_1jRWuXMlzmSSbWp,NaN,...,2,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
30,12/19/2023 14:05,12/19/2023 14:22,0,99.36.20.97,100,1013,1,12/19/2023 14:22,R_3h3WQSyejR1MqXv,NaN,...,1,3,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
31,12/19/2023 14:05,12/19/2023 14:23,0,174.207.160.145,100,1080,1,12/19/2023 14:23,R_7V3bSVZG7DVeNwa,NaN,...,2,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
32,12/19/2023 10:44,12/19/2023 14:23,0,98.219.170.245,100,13139,1,12/19/2023 14:23,R_6lmcAQj0gLBBnWE,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
34,12/19/2023 14:06,12/19/2023 14:25,0,72.132.44.189,100,1119,1,12/19/2023 14:25,R_3Ow4jK6P8PjJkl6,NaN,...,2,2,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
35,12/19/2023 14:09,12/19/2023 14:25,0,73.53.159.133,100,986,1,12/19/2023 14:25,R_1dRDwxLXY5nDcg3,NaN,...,1,3,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
37,12/19/2023 14:06,12/19/2023 14:26,0,67.149.144.8,100,1197,1,12/19/2023 14:26,R_3gRFGlfdK9lXn1V,NaN,...,1,3,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
38,12/19/2023 14:08,12/19/2023 14:27,0,73.139.120.95,100,1145,1,12/19/2023 14:27,R_5EXTK1RRgGHG1HB,NaN,...,1,1,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN
39,12/19/2023 14:06,12/19/2023 14:27,0,108.82.131.8,100,1277,1,12/19/2023 14:27,R_5OU1ZuX0Ol7QOyk,NaN,...,1,1,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
40,12/19/2023 14:08,12/19/2023 14:27,0,67.49.126.95,100,1170,1,12/19/2023 14:27,R_6fkHgzQD2QVSrkA,NaN,...,1,1,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
41,12/19/2023 14:08,12/19/2023 14:28,0,73.214.34.193,100,1197,1,12/19/2023 14:28,R_3T2dvBvW0gMhHup,NaN,...,2,2,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
42,12/19/2023 14:12,12/19/2023 14:28,0,71.193.44.237,100,944,1,12/19/2023 14:28,R_6ZDIRCKi6l7ReCD,NaN,...,1,1,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
43,12/19/2023 14:13,12/19/2023 14:30,0,71.203.29.147,100,1026,1,12/19/2023 14:30,R_1iGKoLq3EFe85mp,NaN,...,1,1,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
44,12/19/2023 14:14,12/19/2023 14:31,0,72.14.101.191,100,1050,1,12/19/2023 14:31,R_5CDmU96Q1ZVgvCx,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
45,12/19/2023 14:21,12/19/2023 14:38,0,75.86.108.124,100,1015,1,12/19/2023 14:38,R_5FQhWbuyo1HmKTM,NaN,...,1,1,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
51,12/19/2023 10:46,12/19/2023 11:03,0,216.245.122.19,95,1029,0,12/19/2023 15:03,R_7CJ8bkaUfWBKDqR,NaN,...,1,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
54,12/19/2023 10:53,12/19/2023 11:14,0,75.27.144.125,95,1228,0,12/19/2023 15:14,R_5NUb0DewH6eUAZb,NaN,...,1,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
56,12/19/2023 15:25,12/19/2023 15:46,0,23.93.215.178,100,1236,1,12/19/2023 15:46,R_67TOQcab6xvTXUj,NaN,...,3,3,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
57,12/19/2023 15:27,12/19/2023 15:48,0,50.53.175.67,100,1299,1,12/19/2023 15:48,R_5o1IySyaQibiIda,NaN,...,1,2,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN
59,12/19/2023 15:54,12/19/2023 16:12,0,71.197.39.138,100,1057,1,12/19/2023 16:12,R_1P12rqkCMn3cY1d,NaN,...,1,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN
79,12/19/2023 22:53,12/20/2023 0:00,0,216.16.0.164,100,4050,1,12/20/2023 0:00,R_7FENpXBwjlAOtWJ,NaN,...,2,2,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN
80,12/20/2023 12:37,12/20/2023 12:53,0,99.9.227.253,100,972,1,12/20/2023 12:53,R_32isJefn1QoWae5,NaN,...,1,3,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN

In [94]:
Tshrt_quedf.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'workerID', 'Q23', 'Q24', 'Q28',
       'Q30', 'Q32', 'Q32_7_TEXT', 'Q34', 'Q34_2_TEXT', 'Q36', 'Q29', 'Q31',
       'Q32.1', 'Q33', 'Q34.1', 'Q35', 'Q36.1', 'Q37', 'Q38', 'Q39', 'Q40',
       'Q41', 'Q42', 'Q43', 'Q44', 'Q45', 'Q46', 'Q47', 'Q48', 'Q49', 'Q50',
       'task launch time_First Click', 'task launch time_Last Click',
       'task launch time_Page Submit', 'task launch time_Click Count', 'SC0',
       'workerID.1', 'assignmentID', 'hitID'],
      dtype='object')

In [110]:
#2-have one dataframe slice for each categories that categorizes Depression, Anxiety, Stress:
dep_df = Tshrt_quedf[["workerID", "Q32", "Q34", "Q39", "Q42", "Q45", "Q46", "Q50"]]
anx_df = Tshrt_quedf[["workerID", "Q31", "Q33", "Q36", "Q38", "Q44", "Q48", "Q49"]]
str_df = Tshrt_quedf[["workerID", "Q29", "Q35", "Q37", "Q40", "Q41", "Q43", "Q47"]]

dep_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/dep_df.csv')
anx_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/anx_df.csv')
str_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/str_df.csv')

In [129]:
#4-have an overall score for the three categories DAS for each participant (calculated in excel) and label them as normal, moderate, severe etc.
dep_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/dep_df.csv')
anx_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/anx_df.csv')
str_csv = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/str_df.csv')

## for dep
dep_csv.loc[dep_csv['Dsum'] <= 9, 'Dlabel'] = 'Normal'
dep_csv.loc[(dep_csv['Dsum'] >= 10) & (dep_csv['Dsum'] <= 13), 'Dlabel'] = 'Mild'
dep_csv.loc[(dep_csv['Dsum'] >= 14) & (dep_csv['Dsum'] <= 20), 'Dlabel'] = 'Moderate'
dep_csv.loc[(dep_csv['Dsum'] >= 21) & (dep_csv['Dsum'] <= 27), 'Dlabel'] = 'Severe'
dep_csv.loc[dep_csv['Dsum'] >= 28, 'Dlabel'] = 'Extreme'

anx_csv.loc[anx_csv['Asum'] <= 7, 'Alabel'] = 'Normal'
anx_csv.loc[(anx_csv['Asum'] >= 8) & (anx_csv['Asum'] <= 9), 'Alabel'] = 'Mild'
anx_csv.loc[(anx_csv['Asum'] >= 10) & (anx_csv['Asum'] <= 14), 'Alabel'] = 'Moderate'
anx_csv.loc[(anx_csv['Asum'] >= 15) & (anx_csv['Asum'] <= 19), 'Alabel'] = 'Severe'
anx_csv.loc[anx_csv['Asum'] >= 20, 'Alabel'] = 'Extreme'

str_csv.loc[str_csv['Ssum'] <= 14, 'Slabel'] = 'Normal'
str_csv.loc[(str_csv['Ssum'] >= 15) & (str_csv['Ssum'] <= 18), 'Slabel'] = 'Mild'
str_csv.loc[(str_csv['Ssum'] >= 19) & (str_csv['Ssum'] <= 25), 'Slabel'] = 'Moderate'
str_csv.loc[(str_csv['Ssum'] >= 26) & (str_csv['Ssum'] <= 33), 'Slabel'] = 'Severe'
str_csv.loc[str_csv['Ssum'] >= 34, 'Slabel'] = 'Extreme'

dep_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/dep_df.csv')
anx_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/anx_df.csv')
str_csv.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/str_df.csv')

In [2]:
#5- create a csv with all the sums and labels (created in excel) along with dur bias scores. Make sure workerID == participant
sum_labels = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/DAS_sumlabels.csv')
newdf = pd.DataFrame(np.repeat(sum_labels.values, 10, axis=0)) # you dont even need to repeat -____-
newdf.columns = sum_labels.columns

bias_df = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/pt_dur_cond.csv')
tst_df = pd.merge(newdf, bias_df, on= 'participant')
tst_df.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/dur_DAS.csv')

In [3]:
bias_df2 = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/r_analysis/utf_emo_dur_anova.csv')
tst_df2 = pd.merge(sum_labels, bias_df2, on= 'participant')
tst_df2.to_csv('/Users/ayesh/Desktop/Gradstuff/duration_judgement/summary/mturk_summary/emoscene_questionnaires/reg_DAS2.csv')

In [12]:
tst_df2

,Unnamed: 0_x,Unnamed: 0.1_x,participant,Dsum,Dlabel,Asum,Alabel,Ssum,Slabel,Unnamed: 0_y,...,the_end_started,the_end_stopped,key_resp_16_keys,key_resp_16_rt,key_resp_16_duration,rho,p_value,zscr,resp_diff,dur_group
0,0,4,A1YSYI926BBOHW,7,Normal,7,Normal,12,Normal,397,...,NaN,NaN,NaN,NaN,NaN,0.916781,1.160000e-53,1.568462,0.364583,short
1,0,4,A1YSYI926BBOHW,7,Normal,7,Normal,12,Normal,398,...,NaN,NaN,NaN,NaN,NaN,0.916781,1.160000e-53,1.568462,1.059028,long
2,0,4,A1YSYI926BBOHW,7,Normal,7,Normal,12,Normal,399,...,NaN,NaN,NaN,NaN,NaN,0.916781,1.160000e-53,1.568462,-0.024306,long
3,0,4,A1YSYI926BBOHW,7,Normal,7,Normal,12,Normal,400,...,NaN,NaN,NaN,NaN,NaN,0.916781,1.160000e-53,1.568462,1.260417,long
4,0,4,A1YSYI926BBOHW,7,Normal,7,Normal,12,Normal,401,...,NaN,NaN,NaN,NaN,NaN,0.916781,1.160000e-53,1.568462,0.340278,long
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,36,80,A3G55RJTW3BSGM,18,Moderate,7,Normal,13,Normal,2369,...,NaN,NaN,NaN,NaN,NaN,0.904252,6.960000e-50,1.495060,2.180556,long
4316,36,80,A3G55RJTW3BSGM,18,Moderate,7,Normal,13,Normal,2370,...,NaN,NaN,NaN,NaN,NaN,0.904252,6.960000e-50,1.495060,0.208333,long
4317,36,80,A3G55RJTW3BSGM,18,Moderate,7,Normal,13,Normal,2371,...,NaN,NaN,NaN,NaN,NaN,0.904252,6.960000e-50,1.495060,0.865741,long
4318,36,80,A3G55RJTW3BSGM,18,Moderate,7,Normal,13,Normal,2372,...,NaN,NaN,NaN,NaN,NaN,0.904252,6.960000e-50,1.495060,0.587963,long
4319,36,80,A3G55RJTW3BSGM,18,Moderate,7,Normal,13,Normal,2374,...,NaN,NaN,NaN,NaN,NaN,0.904252,6.960000e-50,1.495060,0.685185,long